import { expect, test, type Page } from '@playwright/test'
import { addSheet, clickInches, dbg, drawInches, field, isoPoint, makeCube, newSketch, openList, tool } from './helpers'

const view = { cu: 12, cv: 12, scale: 12, su: 1 as const }
const panel = (page: Page, id: string) => page.locator(`[data-panel-id="${id}"]`)
const layout = (page: Page) => page.evaluate(() => JSON.parse(localStorage.getItem('drafter.docks.v1')!))

test.beforeEach(async ({ page }) => {
  await page.goto('/')
  await page.evaluate(() => localStorage.clear())
  await page.reload()
  await page.waitForSelector('.timeline')
})

test('keyboard movement, cancellation, rails, and context changes preserve normal layout and document history', async ({ page }) => {
  await newSketch(page)
  const before = await dbg(page)
  const handle = page.getByRole('button', { name: 'Move Selection', exact: true })
  await handle.focus()
  await page.keyboard.press('Enter')
  await expect(page.locator('.kit-dock-drop[data-target]')).toBeVisible()
  await page.evaluate(() => new Promise<void>(resolve => requestAnimationFrame(() => resolve())))
  await page.keyboard.press('Escape')
  expect((await layout(page)).columns.right).toEqual(['properties', 'selection'])
  await expect(handle).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(page.locator('.kit-dock-drop[data-target]')).toBeVisible()
  await page.evaluate(() => new Promise<void>(resolve => requestAnimationFrame(() => resolve())))
  const destination = page.getByRole('button', { name: 'Move panel before Model in left dock', exact: true })
  for (let i = 0; i < 10 && !await destination.evaluate(el => el === document.activeElement); i++) await page.keyboard.press('Tab')
  await expect(destination).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('complementary', { name: 'left dock' }).getByRole('button', { name: 'Move Selection', exact: true })).toBeVisible()
  await expect(handle).toBeFocused()
  await expect(page.getByRole('status').filter({ hasText: 'Selection moved' })).toContainText('left dock before Model')
  await page.getByRole('button', { name: 'Collapse Selection', exact: true }).click()
  const saved = await layout(page)
  await page.getByRole('button', { name: 'Collapse left dock', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Expand left dock', exact: true })).toBeFocused()
  const rail = page.getByRole('toolbar', { name: 'left dock panels' })
  expect(await rail.getByRole('button').evaluateAll(els => els.map(el => el.getAttribute('aria-label')))).toEqual(['Expand left dock', 'Open Selection', 'Open Model', 'Open Sketch entities'])
  await page.getByRole('button', { name: 'Open Selection', exact: true }).click()
  await expect(panel(page, 'selection')).toContainText('Nothing selected')
  await expect(panel(page, 'model')).toBeHidden()
  await page.getByRole('button', { name: 'Restore Selection layout', exact: true }).click()
  await expect(panel(page, 'selection').locator('.kit-dock-content')).toBeHidden()
  expect(await layout(page)).toEqual(saved)
  const after = await dbg(page)
  expect(after.features).toEqual(before.features)
  expect(after.selection).toEqual(before.selection)
  expect(after.history).toEqual(before.history)
  await page.getByRole('button', { name: 'Finish', exact: true }).click()
  await expect(panel(page, 'entities')).toHaveCount(0)
  await expect(panel(page, 'selection')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Edit sketch', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Edit sketch', exact: true }).click()
  expect((await layout(page)).columns.left).toEqual(['selection', 'model', 'entities'])
  await expect(page.getByRole('button', { name: 'Expand Selection', exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('button', { name: 'Expand Selection', exact: true })).toBeVisible()
  expect(await layout(page)).toEqual(saved)
  await handle.focus()
  await page.keyboard.press('Enter')
  await expect(page.locator('.kit-dock-drop[data-target]')).toBeVisible()
  await page.evaluate(() => new Promise<void>(resolve => requestAnimationFrame(() => resolve())))
  const end = page.getByRole('button', { name: 'Move panel to end of left dock', exact: true })
  for (let i = 0; i < 10 && !await end.evaluate(el => el === document.activeElement); i++) await page.keyboard.press('Tab')
  await expect(end).toBeFocused()
  await page.keyboard.press('Enter')
  await expect.poll(async () => (await layout(page)).columns.left).toEqual(['model', 'entities', 'selection'])
  await expect(handle).toBeFocused()
})

test('pointer movement and dock width preserve sketch scale and accurate picking', async ({ page }) => {
  await newSketch(page)
  await drawInches(page, view, [0, 0], [24, 16])
  const region = page.locator('[data-region]').first()
  const width = (await region.boundingBox())!.width
  await page.getByRole('button', { name: 'Move Selection', exact: true }).dragTo(page.getByRole('button', { name: 'Move panel before Model in left dock', exact: true }), { sourcePosition: { x: 15, y: 10 } })
  await expect.poll(async () => (await layout(page)).columns.left).toEqual(['selection', 'model', 'entities'])
  await page.getByRole('button', { name: 'Move Selection', exact: true }).dragTo(page.getByRole('button', { name: 'Move panel to end of left dock', exact: true }), { sourcePosition: { x: 15, y: 10 } })
  await expect.poll(async () => (await layout(page)).columns.left).toEqual(['model', 'entities', 'selection'])
  const divider = page.getByRole('separator', { name: 'Resize left dock', exact: true })
  await divider.focus()
  await page.keyboard.press('ArrowRight')
  await expect(divider).toHaveAttribute('aria-valuenow', '256')
  const edge = (await divider.boundingBox())!
  await page.mouse.move(edge.x + edge.width / 2, edge.y + 100)
  await page.mouse.down()
  await page.mouse.move(edge.x + 1000, edge.y + 100)
  await page.mouse.up()
  await expect(divider).toHaveAttribute('aria-valuenow', '400')
  await expect.poll(async () => (await page.locator('.centre').boundingBox())!.width).toBeGreaterThanOrEqual(240)
  await page.getByRole('button', { name: 'Collapse right dock', exact: true }).click()
  expect((await region.boundingBox())!.width).toBeCloseTo(width, 0)
  await tool(page, 'Select')
  await clickInches(page, view, 24, 8)
  await expect(field(page, 'Position')).toBeVisible()
  await page.locator('.sketch').click({ position: { x: 20, y: 20 } })
  await page.keyboard.press('f')
  const canvas = (await page.locator('.sketch svg').boundingBox())!
  await expect.poll(async () => (await region.boundingBox())!.width).toBeGreaterThan(width)
  const fitted = (await region.boundingBox())!
  expect(fitted.x + fitted.width / 2).toBeCloseTo(canvas.x + canvas.width / 2, 0)
  expect(fitted.y + fitted.height / 2).toBeCloseTo(canvas.y + canvas.height / 2, 0)
})

test('hidden Selection updates and constraint inspection overrides retained geometry', async ({ page }) => {
  await newSketch(page)
  await drawInches(page, view, [0, 0], [24, 16])
  await tool(page, 'Select')
  await clickInches(page, view, 24, 8)
  await field(page, 'Position').fill('12 + 12')
  await field(page, 'Position').press('Enter')
  await page.getByRole('button', { name: 'Collapse right dock', exact: true }).click()
  await openList(page, 'Constraints')
  await page.getByRole('listbox', { name: 'Constraints' }).getByRole('option', { name: /^l3.at/ }).click()
  expect((await dbg(page)).selection.lineIds).toHaveLength(1)
  await page.getByRole('button', { name: 'Open Selection', exact: true }).click()
  const expression = page.getByRole('textbox', { name: 'Expression', exact: true })
  await expect(expression).toHaveValue('12 + 12')
  await expect(panel(page, 'selection')).toContainText('24"')
  await expect(field(page, 'Position')).toHaveCount(0)
  await expression.fill('missing + 1')
  await expression.press('Enter')
  await expect(panel(page, 'selection')).toContainText(/unknown|undefined|not found/i)
  await expression.fill('12 + 8')
  await expression.press('Enter')
  await expect(panel(page, 'selection')).toContainText('20"')
  await page.getByRole('button', { name: 'Inspect line l3', exact: true }).click()
  expect((await dbg(page)).selection.constraint).toBeUndefined()
  await expect(field(page, 'Position')).toBeVisible()
  await page.getByRole('listbox', { name: 'Constraints' }).getByRole('option', { name: /^l3.at/ }).click()
  await page.getByRole('button', { name: 'Remove constraint', exact: true }).click()
  expect((await dbg(page)).features[0]!.lines[2].at).toBe(320)
  await expect(page.getByRole('button', { name: 'Restore Selection layout', exact: true })).toBeVisible()
})

test('sheet view uses contextual panels and retains zoom when dock bounds change', async ({ page }) => {
  await newSketch(page)
  await page.getByRole('button', { name: 'Finish', exact: true }).click()
  await page.getByRole('button', { name: 'Sheets', exact: true }).click()
  await addSheet(page)
  await expect(panel(page, 'entities')).toHaveCount(0)
  await expect(panel(page, 'selection')).toHaveCount(0)
  const paper = page.locator('.sheet-paper > svg')
  await expect(paper).toBeVisible()
  const width = (await paper.boundingBox())!.width
  await page.getByRole('button', { name: 'Collapse right dock', exact: true }).click()
  await expect.poll(async () => (await page.locator('.sheet-viewport').boundingBox())!.width).toBeGreaterThan(1000)
  expect((await paper.boundingBox())!.width).toBeCloseTo(width, 0)
  await page.getByRole('button', { name: 'Fit (F)', exact: true }).click()
  await expect.poll(async () => (await paper.boundingBox())!.width).toBeGreaterThan(width)
  const before = (await paper.boundingBox())!
  await page.mouse.move(before.x + before.width / 2, before.y + before.height / 2)
  await page.mouse.down({ button: 'middle' })
  await page.mouse.move(before.x + before.width / 2 + 30, before.y + before.height / 2 + 20)
  await page.mouse.up({ button: 'middle' })
  expect((await paper.boundingBox())!.x).toBeCloseTo(before.x + 30, 0)
})

test('model picking and fit use the resized central viewport without changing the camera on resize', async ({ page }) => {
  await makeCube(page)
  const camera = (await dbg(page)).view.camera
  await page.getByRole('button', { name: 'Collapse left dock', exact: true }).click()
  const edge = page.getByRole('separator', { name: 'Resize right dock', exact: true })
  await edge.focus()
  await page.keyboard.press('ArrowLeft')
  await expect(edge).toHaveAttribute('aria-valuenow', '316')
  expect((await dbg(page)).view.camera).toEqual(camera)
  await page.mouse.click(...await isoPoint(page, 12, -12, 24))
  expect((await dbg(page)).selection.bodyId).toBeDefined()
  await page.keyboard.press('f')
  await expect.poll(async () => (await dbg(page)).view.camera.center).toEqual([192, -192, 192])
  const viewport = (await page.locator('.view[data-model-view]').boundingBox())!
  await page.mouse.click(viewport.x + viewport.width / 2, viewport.y + viewport.height / 2)
  expect((await dbg(page)).selection.bodyId).toBeDefined()
})
