import { expect, test } from '@playwright/test'
import { readFile } from 'node:fs/promises'
import { choose, confirmDialog, dbg, field, makeCube, menu } from './helpers'

test('sheets list, settings, navigation, persistence, and standalone export', async ({ page }) => {
  await page.goto('/')
  await makeCube(page)
  await page.getByRole('button', { name: 'Sheets', exact: true }).click()
  await page.getByRole('button', { name: 'Add Sheet', exact: true }).click()
  const drawing = page.locator('.sheet-paper > svg')
  await expect(drawing).toContainText('Sheet 1 of 1')
  await expect(drawing).toContainText('Front')
  await expect(drawing.locator('[data-sheet-view] line')).toHaveCount(4)
  const beforePan = (await drawing.boundingBox())!
  await page.keyboard.down('Space')
  await page.mouse.move(beforePan.x + beforePan.width / 2, beforePan.y + beforePan.height / 2)
  await page.mouse.down()
  await page.mouse.move(beforePan.x + beforePan.width / 2 + 30, beforePan.y + beforePan.height / 2 + 20)
  await page.mouse.up()
  await page.keyboard.up('Space')
  expect((await drawing.boundingBox())!.x).toBeCloseTo(beforePan.x + 30, 0)
  await expect(page.getByRole('listbox', { name: 'Sheets' }).getByRole('option')).toHaveCount(1)
  await field(page, 'Name').fill('Case Front')
  await field(page, 'Name').press('Enter')
  await page.getByRole('button', { name: 'Add Sheet', exact: true }).click()
  await page.getByRole('button', { name: 'Move up', exact: true }).click()
  await expect(page.getByRole('listbox', { name: 'Sheets' }).getByRole('option')).toHaveText(['Sheet 2Front · 1:4', 'Case FrontFront · 1:4'])
  await expect(drawing).toContainText('Sheet 1 of 2')
  await choose(page, 'View', 'Top')
  await expect(drawing.locator('[data-sheet-view]')).toHaveAttribute('data-sheet-view', 'top')
  await expect(drawing).toContainText('Top')
  const camera = (await dbg(page)).view.camera
  await page.keyboard.press('1')
  expect((await dbg(page)).view.camera).toEqual(camera)
  await page.getByRole('button', { name: 'Delete Sheet', exact: true }).click()
  await confirmDialog(page, 'Cancel')
  await expect(page.getByRole('listbox', { name: 'Sheets' }).getByRole('option')).toHaveCount(2)
  await page.getByRole('button', { name: 'Delete Sheet', exact: true }).click()
  await confirmDialog(page, 'Delete')
  await page.keyboard.press('Meta+z')
  await expect(page.getByRole('listbox', { name: 'Sheets' }).getByRole('option')).toHaveCount(2)
  await page.getByRole('option', { name: 'Case Front', exact: true }).click()
  await field(page, 'Name').fill('Renamed')
  await field(page, 'Name').press('Enter')
  await page.getByRole('button', { name: /^Undo/ }).click()
  await expect(field(page, 'Name')).toHaveValue('Case Front')
  await choose(page, 'Scale', /^1:1$/)
  await expect(page.getByText('The view exceeds the drawing area; choose a smaller scale.')).toBeVisible()
  await choose(page, 'Scale', '1:4')
  await drawing.hover()
  await page.mouse.wheel(0, -500)
  await page.getByRole('button', { name: 'Fit (F)', exact: true }).click()
  const paper = (await drawing.boundingBox())!
  const viewport = (await page.locator('.sheet-viewport').boundingBox())!
  expect(paper.width).toBeLessThan(viewport.width)
  expect(paper.height).toBeLessThan(viewport.height)
  await page.mouse.move(paper.x + paper.width / 2, paper.y + paper.height / 2)
  await page.mouse.down({ button: 'middle' })
  await page.mouse.move(paper.x + paper.width / 2 + 40, paper.y + paper.height / 2 + 20)
  await page.mouse.up({ button: 'middle' })
  expect((await drawing.boundingBox())!.x).toBeCloseTo(paper.x + 40, 0)
  await page.keyboard.press('f')
  await page.keyboard.press('Escape')
  await expect(drawing).toHaveCount(0)
  await page.getByRole('option', { name: 'Case Front', exact: true }).click()
  const downloadPromise = page.waitForEvent('download')
  await menu(page, 'Export sheet as SVG')
  const download = await downloadPromise
  expect(download.suggestedFilename()).toBe('Untitled-Case_Front.svg')
  const exported = await readFile((await download.path())!, 'utf8')
  expect(exported).toContain('width="11in" height="8.5in"')
  expect(exported).toContain('Case Front')
  expect(exported).toContain('1:4')
  await page.reload()
  await page.getByRole('button', { name: 'Sheets', exact: true }).click()
  await expect(page.getByRole('listbox', { name: 'Sheets' }).getByRole('option')).toHaveCount(2)
  await page.getByRole('button', { name: 'Model', exact: true }).click()
  await expect(page.locator('.centre canvas')).toBeVisible()
})

test('prints current or ordered sheets with paper-sized pages', async ({ page }) => {
  await page.goto('/')
  await makeCube(page)
  await page.getByRole('button', { name: 'Sheets', exact: true }).click()
  await page.getByRole('button', { name: 'Add Sheet', exact: true }).click()
  await page.getByRole('button', { name: 'Add Sheet', exact: true }).click()
  await choose(page, 'Orientation', 'Portrait')
  await page.getByRole('button', { name: 'Add Sheet', exact: true }).click()
  await page.evaluate(() => { window.print = () => {} })
  await page.getByRole('button', { name: 'Print All', exact: true }).click()
  const pages = page.locator('#sheet-print > section')
  await expect(pages).toHaveCount(3)
  await expect(pages.nth(0)).toContainText('Sheet 1 of 3')
  await expect(pages.nth(1)).toContainText('Sheet 2 of 3')
  await expect(pages.nth(2)).toContainText('Sheet 3 of 3')
  await page.emulateMedia({ media: 'print' })
  await expect(page.locator('#root')).toBeHidden()
  expect((await pages.nth(0).boundingBox())!.width).toBeCloseTo(11 * 96, 0)
  expect((await pages.nth(1).boundingBox())!.width).toBeCloseTo(8.5 * 96, 0)
  const line = pages.nth(0).locator('[data-sheet-view] line').first()
  const length = await line.evaluate((element) => {
    const segment = element as SVGLineElement
    const matrix = segment.getScreenCTM()!
    const first = new DOMPoint(segment.x1.baseVal.value, segment.y1.baseVal.value).matrixTransform(matrix)
    const second = new DOMPoint(segment.x2.baseVal.value, segment.y2.baseVal.value).matrixTransform(matrix)
    return Math.hypot(second.x - first.x, second.y - first.y)
  })
  expect(length).toBeCloseTo(6 * 96, 0)
  const pdf = await page.pdf({ path: 'test-results/sheets-print.pdf', preferCSSPageSize: true })
  expect(pdf.toString('latin1').match(/\/Type \/Page\b/g)).toHaveLength(3)
  expect(pdf.toString('latin1')).toContain('/MediaBox [0 0 792 612]')
  expect(pdf.toString('latin1')).toContain('/MediaBox [0 0 612 792]')
  await page.evaluate(() => window.dispatchEvent(new Event('afterprint')))
  await expect(page.locator('#sheet-print')).toHaveCount(0)
  await page.emulateMedia({ media: 'screen' })
  await page.getByRole('option', { name: 'Sheet 2', exact: true }).click()
  await page.getByRole('button', { name: 'Print Sheet', exact: true }).click()
  await expect(page.locator('#sheet-print > section')).toHaveCount(1)
  await expect(page.locator('#sheet-print')).toContainText('Sheet 2 of 3')
  await page.evaluate(() => window.dispatchEvent(new Event('beforeprint')))
  await expect(page.locator('#sheet-print > section')).toHaveCount(1)
  await page.evaluate(() => window.dispatchEvent(new Event('afterprint')))
  await page.evaluate(() => window.dispatchEvent(new Event('beforeprint')))
  await expect(page.locator('#sheet-print > section')).toHaveCount(1)
  await expect(page.locator('#sheet-print')).toContainText('Sheet 2 of 3')
  await page.emulateMedia({ media: 'print' })
  await expect(page.locator('#root')).toBeHidden()
  await expect(page.locator('#sheet-print')).toBeVisible()
  await page.evaluate(() => window.dispatchEvent(new Event('afterprint')))
  await page.emulateMedia({ media: 'screen' })
  await page.keyboard.press('Escape')
  await page.evaluate(() => window.dispatchEvent(new Event('beforeprint')))
  await page.emulateMedia({ media: 'print' })
  await expect(page.locator('#root')).toBeVisible()
  await expect(page.locator('#sheet-print')).toHaveCount(0)
})
